#!/usr/bin/env python3

import os
import shutil
import subprocess
import sys
from pathlib import Path

CONFIGS = {
    "both": {
        "name": "PT + AR",
        "herbie": "-mllvm --fpopt-enable-herbie=1",
        "pt": "-mllvm --fpopt-enable-pt",
        "herbie_flag": "--fpopt-enable-herbie=1",
        "pt_flag": "--fpopt-enable-pt",
        "output": "both.pkl",
    },
    "pt": {
        "name": "PT only",
        "herbie": "-mllvm --fpopt-enable-herbie=0",
        "pt": "-mllvm --fpopt-enable-pt",
        "herbie_flag": "--fpopt-enable-herbie=0",
        "pt_flag": "--fpopt-enable-pt",
        "output": "pt.pkl",
    },
    "rewrites": {
        "name": "AR only (Herbie)",
        "herbie": "-mllvm --fpopt-enable-herbie=1",
        "pt": "-mllvm --fpopt-enable-pt=0",
        "herbie_flag": "--fpopt-enable-herbie=1",
        "pt_flag": "--fpopt-enable-pt=0",
        "output": "rewrites.pkl",
    },
}

MAKEFILE = "Makefile"
MAKEFILE_BACKUP = "Makefile.backup"
RUNPY = "run.py"
RUNPY_BACKUP = "run.py.backup"
MEASUREMENTS = "measurements.pkl"

CLEANUP_DIRS = ["tmp", "logs", "outputs", "plots"]
CLEANUP_CACHE_FILES = ["cache/budgets.txt", "cache/table.json"]


def backup_files():
    shutil.copy(MAKEFILE, MAKEFILE_BACKUP)
    shutil.copy(RUNPY, RUNPY_BACKUP)


def restore_files():
    if os.path.exists(MAKEFILE_BACKUP):
        shutil.copy(MAKEFILE_BACKUP, MAKEFILE)
    if os.path.exists(RUNPY_BACKUP):
        shutil.copy(RUNPY_BACKUP, RUNPY)


def cleanup_directories():
    for dir_name in CLEANUP_DIRS:
        if os.path.exists(dir_name):
            try:
                shutil.rmtree(dir_name)
            except Exception as e:
                print(f"  ✗ Warning: Could not remove {dir_name}/: {e}")

    for file_path in CLEANUP_CACHE_FILES:
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception as e:
                print(f"  ✗ Warning: Could not remove {file_path}: {e}")


def update_makefile(config):
    with open(MAKEFILE_BACKUP, "r") as f:
        content = f.read()

    lines = content.split("\n")
    new_lines = []

    for line in lines:
        if "--fpopt-enable-herbie" in line and "dquat-fpopt.exe" not in line:
            if "--fpopt-enable-herbie=1" in line:
                line = line.replace(
                    "--fpopt-enable-herbie=1", f'--fpopt-enable-herbie={1 if "=1" in config["herbie"] else 0}'
                )
            elif "--fpopt-enable-herbie=0" in line:
                line = line.replace(
                    "--fpopt-enable-herbie=0", f'--fpopt-enable-herbie={1 if "=1" in config["herbie"] else 0}'
                )
            else:
                new_lines.append(f'\t\t{config["herbie"]} \\')
                continue

        if "--fpopt-enable-pt" in line and "dquat-fpopt.exe" not in line:
            if "=0" in config["pt"]:
                line = line.replace("--fpopt-enable-pt", "--fpopt-enable-pt=0")
            else:
                line = line.replace("--fpopt-enable-pt=0", "--fpopt-enable-pt")

        new_lines.append(line)

    with open(MAKEFILE, "w") as f:
        f.write("\n".join(new_lines))


def update_runpy(config):
    with open(RUNPY_BACKUP, "r") as f:
        content = f.read()

    lines = content.split("\n")
    new_lines = []

    for line in lines:
        if '"--fpopt-enable-herbie' in line:
            new_lines.append(f'    "{config["herbie_flag"]}",')
        elif '"--fpopt-enable-pt' in line:
            new_lines.append(f'    "{config["pt_flag"]}",')
        else:
            new_lines.append(line)

    with open(RUNPY, "w") as f:
        f.write("\n".join(new_lines))


def run_command(cmd, description):
    try:
        result = subprocess.run(
            cmd, shell=isinstance(cmd, str), check=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
        )
        print(result.stdout)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error during: {description}")
        print(e.stdout)
        return False


def run_configuration(config_key, config):
    update_makefile(config)
    update_runpy(config)
    cleanup_directories()

    if not run_command("make clean", "Running make clean"):
        print("  ✗ Warning: make clean failed, continuing anyway...")
    if not run_command("make", "Running make"):
        return False

    if not os.path.exists("cache/budgets.txt"):
        print("  ✗ Error: cache/budgets.txt was not generated by make")
        print("  This is a critical error - the compilation should have created this file")
        return False

    if not run_command(["python3", "run.py"], "Compiling all budget variants"):
        print("  ✗ Warning: Some compilations may have failed")

    if not run_command(["python3", "benchmark.py"], "Running benchmarks"):
        return False

    if not os.path.exists(MEASUREMENTS):
        print(f"  ✗ Error: {MEASUREMENTS} was not created")
        return False

    if os.path.exists(config["output"]):
        os.remove(config["output"])
    shutil.move(MEASUREMENTS, config["output"])

    cleanup_directories()
    return True


def main():
    if not os.path.exists(MAKEFILE) or not os.path.exists(RUNPY):
        print("Error: Makefile or run.py not found in current directory")
        print("Please run this script from the dquat directory")
        sys.exit(1)

    backup_files()

    success_count = 0
    failed_configs = []

    try:
        for config_key in ["both", "pt", "rewrites"]:
            config = CONFIGS[config_key]
            if run_configuration(config_key, config):
                success_count += 1
                print(f"\n✓ Successfully completed: {config['name']}")
            else:
                failed_configs.append(config["name"])
                print(f"\n✗ Failed: {config['name']}")
                print("Continuing with remaining configurations...")

    finally:
        restore_files()

    if failed_configs:
        print(f"Failed configurations: {', '.join(failed_configs)}")
    else:
        print("All configurations completed successfully!")
    print(f"\nResults saved in current directory:")
    print("  - both.pkl (PT + AR)")
    print("  - pt.pkl (PT only)")
    print("  - rewrites.pkl (AR only)")
    print("=" * 60)

    if success_count == 3 and not failed_configs:
        print("\n" + "=" * 60)
        print("Running ablation analysis and plotting...")
        print("=" * 60)
        try:
            result = subprocess.run(["python3", "plot.py"], check=True, text=True)
            print("\n✓ Ablation analysis completed successfully!")
        except subprocess.CalledProcessError as e:
            print(f"\n✗ Error running plot.py: {e}")
        except FileNotFoundError:
            print("\n✗ plot.py not found in current directory")
    else:
        print("\nSkipping plot.py - not all configurations succeeded")
        print("You can manually run: python3 plot.py")

    print("=" * 60)


if __name__ == "__main__":
    main()
